# Generated by Django 5.1.4 on 2025-01-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_media', models.CharField(max_length=150)),
                ('dateEmprunt', models.DateTimeField(auto_now_add=True, null=True)),
                ('name_emprunteur', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_media', models.CharField(max_length=150)),
                ('auteur', models.CharField(max_length=150)),
                ('media_type', models.CharField(choices=[('livre', 'Livres'), ('dvd', 'DVD'), ('cd', 'CD'), ('jeu_plateau', 'Jeu Plateau')], max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
